[package]
name = "ralias"
version = "0.1.0"
edition = "2018"
authors = ["liutong"]

[lib]
name = "ralias"
crate-type = ["staticlib","rlib"]

[dependencies]
libc = "*"
rcmd = {path="../cmd"}
rcommon= {path="../common"}
rhelp = {path ="../help"}
# nix = "*"
