[package]
name = "rcolon"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib","rlib"]
name = "rcolon"

[dependencies]
libc = "*"
rcommon = {path ="../common"}
rhelp = {path ="../help"}
